apiVersion: com.datastax.oss/v1alpha1
kind: PulsarCluster
metadata:
  name: pulsar-cluster
spec:
  global:
    name: pulsar
    image: datastax/lunastreaming-all:2.10_2.5
    storage:
      existingStorageClassName: default
  zookeeper:
    replicas: 3
    dataVolume:
      size: 5Gi
    resources:
      requests:
        cpu: "0.5"
  bookkeeper:
    replicas: 3
    volumes:
      journal:
        size: 20Gi
      ledgers:
        size: 20Gi
    resources:
      requests:
        cpu: "0.5"
  broker:
    replicas: 3
    autoscaler:
      enabled: false
      periodMs: 20000
      min: 3
      max: 10
      lowerCpuThreshold: 0.1
      higherCpuThreshold: 0.4
      scaleUpBy: 1
      scaleDownBy: 1
      stabilizationWindowMs: 300000
  proxy:
    replicas: 2
    resources:
      requests:
        cpu: "0.5"
  functionsWorker:
    replicas: 2
    runtime: kubernetes
    resources:
      requests:
        cpu: "0.5"
    config:
      numFunctionPackageReplicas: "2"


